devsonly_web/devsonly_web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main.views.index import index_page
from main.views.registration import login_page, registration_page
from main.views.social import show_post_page, add_post_page, users_page
from main.views.social import add_post_page, users_page, edit_post_page
from main.views.user import author_rating_page, team_member_rating_page
from main.views.user import profile_page
from main.views.registration import registration_page, login_page
from main.views.registration import registration_page
from main.views.social import *
from main.views.user import profile_page, edit_profile_page
from main.views.admin import userlist_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page),
    path('registration/',
         registration_page,
         name='registration'),
    path('login/',
         login_page,
         name='login'),
    path('post/add/',
         author_rating_page,
         name='author_rating'),
    path('rating/member/',
         team_member_rating_page,
         name='team_member_rating'),
    path('users/list/',
         users_page,
         name='users'),
    path('post/<int:post_id>/',
         show_post_page,
         name='show_post'),
    path('profile/',
         profile_page,
         name='profile'),
    path('edit_profile/<int:user_id>/',
         edit_profile_page,
         name='edit_profile'),
    path('login/',
        login_page,
        name='login'),
    path('post/edit/<int:post_id>/',
         edit_post_page,
         name='edit_post'),
    path('userlist/',
         userlist_page,
         name='userlist'),
    ]+static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

devsonly_web/main/forms/admin.py
from django import forms


class BanTimeForm(forms.Form):
    BanSeconds = forms.IntegerField(required=False)


class MuteTimeForm(forms.Form):
    MuteSeconds = forms.IntegerField(required=False)

devsonly_web/main/forms/registration.py
from django import forms
from django.core.exceptions import ValidationError

from src.registration import (validate_letters, validate_username,
                              validate_email, validate_password,
                              validate_birth_date)


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username',
                               max_length=16,
                               validators=[validate_username])
    email = forms.EmailField(label='Email',
                             validators=[validate_email])
    password = forms.CharField(label='Password',
                               max_length=24,
                               widget=forms.PasswordInput,
                               validators=[validate_password])
    double_password = forms.CharField(label='Repeat password',
                                      max_length=24,
                                      widget=forms.PasswordInput)
    first_name = forms.CharField(label='First name',
                                 max_length=24,
                                 validators=[validate_letters],
                                 required=False)
    last_name = forms.CharField(label='Last name',
                                max_length=24,
                                validators=[validate_letters],
                                required=False)
    date_of_birth = forms.DateField(label='Date of birth',
                                    widget=forms.DateInput(attrs={'placeholder': 'DD-MM-YY'}),
                                    input_formats=['%d-%m-%Y'],
                                    validators=[validate_birth_date],
                                    required=False)
    subjective = forms.CharField(label='Subjective',
                                 max_length=16,
                                 widget=forms.TextInput(attrs={'placeholder': 'they',
                                                               'class': 'form-control'}),
                                 validators=[validate_letters],
                                 required=False)
    objective = forms.CharField(label='Objective',
                                max_length=16,
                                widget=forms.TextInput(attrs={'placeholder': 'them',
                                                              'class': 'form-control'}),
                                validators=[validate_letters],
                                required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        double_password = cleaned_data.get('double_password')

        if password and password != double_password:
            self.add_error('password',
                           ValidationError('Passwords do not match.',
                                           code='no match'))


class Login(forms.Form):
    username = forms.CharField(max_length=255,
                               label='Username')
    password = forms.CharField(max_length=255,
                               widget=forms.PasswordInput,
                               label='Password')

devsonly_web/main/forms/social.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q
from main.models import PostMedia


class PostForm(forms.Form):
    """! PostForm class
    """
    text = forms.CharField(label='Text',
                           widget=forms.TextInput(attrs={'placeholder': 'Write your text here...'}),
                           required=False)
    file = forms.FileField(label='Upload file',
                           widget=forms.ClearableFileInput(attrs={'multiple': True}),
                           required=False)
    comment_type = forms.ChoiceField(label='Comments type',
                                     choices=[(0, 'Anonymous'),
                                              (1, 'Not Anonymous')])

    def clean(self) -> None:
        cd = super().clean()
        block_fields = [cd.get('text'),
                        cd.get('image'),
                        cd.get('audio'),
                        cd.get('video'),
                        cd.get('file')]
        if all(field is None or field == '' for field in block_fields):
            raise ValidationError('Block can not be empty',
                                  code='empty block')


class SkillsForm(forms.Form):
    """! SkillsForm class
    """
    requested_skills = forms.CharField(widget=forms.HiddenInput)


class CommentForm(forms.Form):
    """! CommentForm class
    """
    text = forms.CharField(label='Text',
                           widget=forms.TextInput(attrs={'placeholder': 'Write here...'}),
                           required=False)
    file = forms.FileField(label='Upload file',
                           widget=forms.ClearableFileInput(attrs={'multiple': True}),
                           required=False)

    def clean(self):
        cd = super().clean()
        text = cd.get('text')
        file = cd.get('file')
        if text == '' and file is None:
            raise ValidationError('You can not save empty comment',
                                  code='empty')


class EditPostForm(forms.Form):
    """! EditPostForm class
    """
    text = forms.CharField(label='Change text',
                           required=False)
    new_media = forms.FileField(label='Add file',
                                widget=forms.ClearableFileInput(attrs={'multiple': True}),
                                required=False)
    deleted_media = forms.CharField(widget=forms.HiddenInput,
                                    required=False)

    def clean_deleted_media(self) -> forms.CharField:
        cleaned_data = super().clean()
        deleted_media = cleaned_data.get('deleted_media').split()
        for dm in deleted_media:
            if not PostMedia.objects.filter(Q(image=dm) |
                                            Q(audio=dm) |
                                            Q(video=dm) |
                                            Q(file=dm)).exists():
                raise ValidationError('Invalid value',
                                      code='invalid')
        return deleted_media

devsonly_web/main/views/admin.py
from datetime import date, datetime, timedelta, timezone

from django.shortcuts import render
from django.contrib import messages

from src.logger import init_logger
from main.models import User, BannedIPs
from main.forms.admin import BanTimeForm, MuteTimeForm


def index_page(request) -> None:

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(type(ip))

    return render(request, 'pages/index.html')


def userlist_page(request) -> None:
    context = {}
    logger = init_logger(__name__)

    if request.method == 'POST':
        if 'moder toggle' in request.POST:
            user = User.objects.get(id=request.POST['moder toggle'])
            user.is_moder = not user.is_moder
            user.save()

        if 'staff toggle' in request.POST:
            user = User.objects.get(id=request.POST['staff toggle'])
            user.is_staff = not user.is_staff
            user.save()

        if 'warning' in request.POST:
            user = User.objects.get(id=request.POST['warning'])
            user.nwarns += 1
            if user.nwarns == 3:
                user.is_banned = True
            user.save()

        if 'ban toggle' in request.POST:
            user = User.objects.get(id=request.POST['ban toggle'])
            ban_form = BanTimeForm(request.POST)
            if not user.is_banned:
                if ban_form.is_valid():
                    if not user.is_banned:
                        if ban_form.cleaned_data['BanSeconds'] is not None:
                            if ban_form.cleaned_data['BanSeconds'] > 0:
                                user.is_banned = True
                                user.nwarns = 0
                                now = datetime.now(tz=timezone(timedelta(seconds=0)))
                                delta = timedelta(seconds=ban_form.cleaned_data['BanSeconds'])
                                user.unban_date = now + delta
                            elif ban_form.cleaned_data['BanSeconds'] == 0:
                                user.is_banned = True
                                user.nwarns = 0
                            else:
                                messages.error(request, 'The number can not be negative')
                else:
                    messages.error(request, 'Enter valid time')
            else:
                user.is_banned = False
                user.unban_date = None
            context.update({'form': ban_form})
            user.save()

        if 'mute toggle' in request.POST:
            user = User.objects.get(id=request.POST['mute toggle'])
            mute_form = MuteTimeForm(request.POST)
            if not user.is_muted:
                if mute_form.is_valid():
                    if not user.is_muted:
                        if mute_form.cleaned_data['MuteSeconds'] is not None:
                            if mute_form.cleaned_data['MuteSeconds'] > 0:
                                user.is_muted = True
                                now = datetime.now(tz=timezone(timedelta(seconds=0)))
                                delta = timedelta(seconds=mute_form.cleaned_data['MuteSeconds'])
                                user.unmute_date = now + delta
                            elif mute_form.cleaned_data['MuteSeconds'] == 0:
                                user.is_muted = True
                            else:
                                messages.error(request, 'The number can not be negative')
                else:
                    messages.error(request, 'Enter valid time')
            else:
                user.is_muted = False
                user.unmute_date = None
            context.update({'form': mute_form})
            user.save()

        if 'delete' in request.POST:
            user = User.objects.get(id=request.POST['delete'])
            user.delete()

        if 'ip ban' in request.POST:
            user = User.objects.get(id=request.POST['ip ban'])
            ip = BannedIPs(IP=user.reg_ip)
            user.is_banned = True
            user.save()
            ip.save()
        users = User.objects.all()
        context.update({
            'users': users,
            'ban_form': BanTimeForm(),
            'mute_form': MuteTimeForm(),
        })

    elif request.user.is_superuser or request.user.is_staff:
        users = User.objects.all()
        context.update({
            'users': users,
            'ban_form': BanTimeForm(),
            'mute_form': MuteTimeForm(),
        })
    else:
        messages.add_message(request, messages.ERROR, 'You do not have the permissions to view this page')

    return render(request, 'pages/userlist.html', context)

devsonly_web/main/views/index.py
from django.shortcuts import render
from src.logger import init_logger


def index_page(request) -> None:
    # logger = init_logger(__name__)

    # logger.info('info')
    # logger.warning('warning')
    # logger.debug('debug')
    # logger.error('error')
    # logger.critical('critical')

    return render(request, 'pages/index.html')

devsonly_web/main/views/message.py
from django.shortcuts import render


def index_page(request) -> None:

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(type(ip))

    return render(request, 'pages/index.html')

devsonly_web/main/views/registration.py
from datetime import date, datetime, timezone, timedelta

from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect

from main.forms.registration import RegistrationForm, Login
from main.models import User, UserSettings, BannedIPs
from src.common import get_ip
from src.logger import init_logger


def registration_page(request) -> None:
    logger = init_logger(__name__)

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User(reg_ip=get_ip(request),
                        username=cd['username'],
                        email=cd['email'],
                        password=make_password(cd['password']),
                        first_name=cd['first_name'],
                        last_name=cd['last_name'],
                        date_of_birth=cd['date_of_birth'],
                        date_joined=date.today(),
                        )
            user.save()

            user_settings = UserSettings(user=User.objects.get(username=user.username),
                                         sex=f'{cd["subjective"]}/{cd["objective"]}',
                                         )
            user_settings.save()

            logger.info('Successful registration.')
            return redirect('/')
        else:
            for field in form:
                if field.errors:
                    for error in field.errors:
                        messages.error(request, f'{field.label}: {error}')
    else:
        form = RegistrationForm()
    context = {'pagename': 'Registration',
               'form': form,
               }
    return render(request, 'pages/registration.html', context)


def login_page(request) -> None:
    context = {
        'pagename': 'Authorization'
    }
    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request,
                                username=data['username'],
                                password=data['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                messages.add_message(request,
                                     messages.ERROR,
                                     "Неверный логин или пароль")
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 "Неверный формат данных")
    else:
        form = Login()
    context.update({
        'form': form,
    })
    return render(request, 'pages/login.html', context)

devsonly_web/main/templates/pages/add_post.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="main_container">
        <div class="form_container">
            <h1>Post Add</h1>
            {% if messages %}
                <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
                <br><br>
            {% endif %}

            <form action="/post/add/" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% if post_form.non_field_errors %}
                    <ul>
                        {% for error in non_field_errors.as_text %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% for field in post_form %}
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <label class="field_label">{{ field.label }}:</label>
                    <br>
                    {{ field }}
                    <br><br>
                {% endfor %}

                <input class="submit_button" type="submit" value="Create block">
            </form>
        </div>

        {% if post %}
            <div class="post_container">
                <p>Posted by <span style="color: #009778">{{ post.author }}</span></p>
                <p>{{ post.text }}</p>

                {% if images %}
                    <div class="images_cont">
                        {% for image in images %}
                            <img class="post_image" src="{{ image.file.url }}">
                        {% endfor %}
                    </div>
                {% endif %}

                {% if audios %}
                    <div style="margin-top: 10px;">
                        {% for audio in audios %}
                            <audio controls>
                                <source src="{{ audio.file.url }}">
                            </audio>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if videos %}
                    <div class="images_cont">
                        {% for video in videos %}
                            <video class="post_image" controls>
                                <source src="{{ video.file.url }}">
                            </video>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if files %}
                    {% for file in files %}
                        <a href="{{ file.file.url }}" style="text-decoration: none; color:#009778; margin-top: 10px; font-style: italic;">
                            {{ file.name }}
                        </a>
                    {% endfor %}
                {% endif %}
                <div class="reactions_cont">
                    <p><i class="fa-solid fa-heart"></i> {{ post.likes }}</p>
                    <p><i class="fa-solid fa-heart-crack"></i> {{ post.dislikes }}</p>
                </div>
                <div class="dates">
                    <p>Created: {{ post.created }}</p>
                    <p>Last modified: {{ post.modified }}</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

devsonly_web/main/templates/pages/author_rating.html
{% extends 'base/base.html' %}

{% block content %}
<div class="table_container">
    <table>
        {% for user in author_rating %}
            <tr>
                <td>{{ user.id }}</td>
                <td><a href="#">{{ user.username }}</a></td>
                <td style="color: #009778;">{{ user.author_rating }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
<script>
    'use strict'
    let places = document.getElementsByClassName('ratingPlace');
    places[0].style.color = '#FFD700';
    places[1].style.color = '#C0C0C0';
    places[2].style.color = '#CD7F32';
    
</script>
{% endblock %}

devsonly_web/main/templates/pages/edit_post.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="main_container">
        <div class="form_cont">
            <h1>Edit Post</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="text_block">
                    {{ edit_form.text.label }}:
                    <br>
                    {{ edit_form.text }}
                </div>
                

                {% if images %}
                    {% for image in images %}
                        <div>
                            <p class="file_name">{{ image.name }}</p>
                            <img class="media_cont" src="{{ image.file.url }}">
                            <br>
                            <input class="post_button" type="button" value="Delete" onclick="deleteMedia(this)">
                            <br>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if audios %}
                    {% for audio in audios %}
                        <div>
                            <p class="file_name">{{ audio.name }} </p>
                            <audio class="audio_cont" controls>
                                <source src="{{ audio.file.url }}">
                            </audio>
                            <br>
                            <input class="post_button" type="button" value="Delete" onclick="deleteMedia(this)">
                            <br>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if videos %}
                    {% for video in videos %}
                        <div>
                            <p class="file_name">{{ video.name }}</p>
                            <video class="media_cont" controls>
                                <source src="{{ video.file.url }}">
                            </video>
                            <br>
                            <input class="post_button" type="button" value="Delete" onclick="deleteMedia(this)">
                            <br>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if files %}
                    {% for file in files %}
                        <div>
                            <a style="text-decoration: none; color: #009778; font-style: italic;" href="{{ file.file.url }}">
                                {{ file.name }}
                            </a>
                            <br>
                            <input class="post_button" type="button" value="Delete" onclick="deleteMedia(this)">
                            <br>
                        </div>
                    {% endfor %}
                {% endif %}
                <br>
                {{ edit_form.new_media.label }}: {{ edit_form.new_media }}
                {{ edit_form.deleted_media }}
                <br>

                <input class="post_button" type="submit" value="Save">
            </form>
        </div>
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <script>
        'use strict';

        document.getElementById('id_text').value = '{{ post.text }}';

        function deleteMedia(element){
            let link = '';
            if (element.parentElement.querySelector('[src]')){
                link = element.parentElement.querySelector('[src]').src;
            }
            if (element.parentElement.querySelector('[href]')){
                link = element.parentElement.querySelector('[href]').href;
            }

            let media = link.slice(link.indexOf('post/'));
            document.getElementById('id_deleted_media').value += `${media} `;
            console.log(`Deleting ${media}`);
            element.parentElement.remove();
        }

    </script>
{% endblock %}

devsonly_web/main/templates/pages/index.html
{% extends 'base/base.html' %}

{% block content %}
<div class="main_container">
    <div class="mainLogo">
        <div class="wellcum">
            <h1 class="wellcum_text"><span class="wellcum_logo">Devs0n1y</span> — unites developers around <span
                    class="world">the world...</span>
            </h1>
        </div>
    </div>
</div>
   
{% endblock %}

devsonly_web/main/templates/pages/login.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="login_cont">
        <form action = '/login/' method = 'POST'>
            {% csrf_token %}
            {% for item in form %}
            <div class="wellcum_imp">
            {{ item.label }} {{ item }}
            </div>
            {% endfor %}
          <input type="submit" value="Login" class="wellcum_button">
        </form>
        <br>
        <br>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endblock %}

devsonly_web/main/templates/pages/post.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="main_container">
        <div class="form_container">
            {% if messages %}
                <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
                <br><br>
            {% endif %}


        </div>

        {% if post %}
            <div class="post_container">
                <p>Posted by <span style="color: #009778">{{ post.author }}</span></p>
                <p>{{ post.text }}</p>

                {% if images %}
                    <div class="images_cont">
                        {% for image in images %}
                            <img class="post_image" src="{{ image.file.url }}">
                        {% endfor %}
                    </div>
                {% endif %}

                {% if audios %}
                    <div style="margin-top: 10px;">
                        {% for audio in audios %}
                            <audio controls>
                                <source src="{{ audio.file.url }}">
                            </audio>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if videos %}
                    <div class="images_cont">
                        {% for video in videos %}
                            <video class="post_image" controls>
                                <source src="{{ video.file.url }}">
                            </video>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if files %}
                    {% for file in files %}
                        <a href="{{ file.file.url }}" style="text-decoration: none; color:#009778; margin-top: 10px; font-style: italic;">
                            {{ file.name }}
                        </a>
                    {% endfor %}
                {% endif %}
                <div class="reactions_cont">
                    <form action="/post/{{ post.id }}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="reaction_btn"><p><i class="fa-solid fa-heart"></i> {{ post.likes }}</p></button>
                        <button type="submit" class="reaction_btn"><p><i class="fa-solid fa-heart-crack"></i> {{ post.dislikes }}</p></button>
                    </form>
                </div>
                <div class="dates">
                    <p>Created: {{ post.created }}</p>
                    <p>Last modified: {{ post.modified }}</p>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

devsonly_web/main/templates/pages/profile.html
{% extends "base/base.html" %}
{% block content %}

<div class="main_profile_container">
    <div class="profile_info_container">
        <div class="left_info_cont">
            {% for item in user_data %}
                {% if item.label == "Profile picture" and item.access == 1 %}
                    <img src="{{ item.data }}" alt="">
                {% endif %}
            {% endfor %}
            <div class="soc_icons">
                <div class="soc_link"></div>
                <div class="soc_link"></div>
                <div class="soc_link"></div>
            </div>
            <p>Socials</p>
            <div class="edit_profile_btn"><a href="/edit_profile/">Edit</a></div>
        </div>
        <div class="right_info_block">
            <p class="user_inf_p">{{ first_name }} {{last_name}}</p>
            <p class="user_inf_p" style="font-size:22px">Nick: <span style="color:#009778">Username</span></p>

            {% for item in user_data %}
                {% if item.access == 1 and item.label != "Profile picture" %}
                    <p class="user_inf_p" style="font-size: 22px">{{item.label}}: <span
                        style="color:#009778">{{ item.data }}</span></p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

devsonly_web/main/templates/pages/registration.html
{% extends 'base/base.html' %}
    {% block content %}
        <div class="wellcum_bod">
            <form action="/registration/" method="POST" class="wellcum_block">
                {% csrf_token %}
                <h1 class="Reg_logo">Registration</h1>
                <input type="text" name="username" placeholder="username" maxlength="16" required="" id="id_username" class="wellcum_imp">
                <br>
                <input type="email" name="email" placeholder="email" required="" id="id_email" class="wellcum_imp">
                <br>
                <input type="password" name="password" placeholder="password" maxlength="24" required="" id="id_password" class="wellcum_imp">
                <br>
                <input type="password" name="double_password" placeholder="password again" maxlength="24" required="" id="id_double_password" class="wellcum_imp">
                <br>
                <form>
                    <div style="display:flex; flex-direction:row; justify-content:space-between;">
                        <input type="submit" value="Registration" class="wellcum_button" onclick=location.href="/login/">
                        <input style="width:40%; color: #fff;
    background-color: #009778;" type="submit" value="Or login" class="wellcum_button" onclick=location.href="/login/" id="LG">
                    </div>
                </form>
            </form>
        </div>
    {% endblock %}